// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: chat.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatService_SendPrivateMessage_FullMethodName    = "/chat.ChatService/SendPrivateMessage"
	ChatService_GetPrivateChatHistory_FullMethodName = "/chat.ChatService/GetPrivateChatHistory"
	ChatService_SearchPrivateMessages_FullMethodName = "/chat.ChatService/SearchPrivateMessages"
	ChatService_RevokePrivateMessage_FullMethodName  = "/chat.ChatService/RevokePrivateMessage"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ... existing code ...
type ChatServiceClient interface {
	// 发送私聊消息
	SendPrivateMessage(ctx context.Context, in *SendPrivateMessageRequest, opts ...grpc.CallOption) (*SendPrivateMessageResponse, error)
	// 获取私聊历史
	GetPrivateChatHistory(ctx context.Context, in *GetPrivateChatHistoryRequest, opts ...grpc.CallOption) (*GetPrivateChatHistoryResponse, error)
	// 搜索私聊消息
	SearchPrivateMessages(ctx context.Context, in *SearchPrivateMessagesRequest, opts ...grpc.CallOption) (*SearchPrivateMessagesResponse, error)
	// 撤回消息
	RevokePrivateMessage(ctx context.Context, in *RevokePrivateMessageRequest, opts ...grpc.CallOption) (*RevokePrivateMessageResponse, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) SendPrivateMessage(ctx context.Context, in *SendPrivateMessageRequest, opts ...grpc.CallOption) (*SendPrivateMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendPrivateMessageResponse)
	err := c.cc.Invoke(ctx, ChatService_SendPrivateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetPrivateChatHistory(ctx context.Context, in *GetPrivateChatHistoryRequest, opts ...grpc.CallOption) (*GetPrivateChatHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrivateChatHistoryResponse)
	err := c.cc.Invoke(ctx, ChatService_GetPrivateChatHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SearchPrivateMessages(ctx context.Context, in *SearchPrivateMessagesRequest, opts ...grpc.CallOption) (*SearchPrivateMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchPrivateMessagesResponse)
	err := c.cc.Invoke(ctx, ChatService_SearchPrivateMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) RevokePrivateMessage(ctx context.Context, in *RevokePrivateMessageRequest, opts ...grpc.CallOption) (*RevokePrivateMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokePrivateMessageResponse)
	err := c.cc.Invoke(ctx, ChatService_RevokePrivateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility.
//
// ... existing code ...
type ChatServiceServer interface {
	// 发送私聊消息
	SendPrivateMessage(context.Context, *SendPrivateMessageRequest) (*SendPrivateMessageResponse, error)
	// 获取私聊历史
	GetPrivateChatHistory(context.Context, *GetPrivateChatHistoryRequest) (*GetPrivateChatHistoryResponse, error)
	// 搜索私聊消息
	SearchPrivateMessages(context.Context, *SearchPrivateMessagesRequest) (*SearchPrivateMessagesResponse, error)
	// 撤回消息
	RevokePrivateMessage(context.Context, *RevokePrivateMessageRequest) (*RevokePrivateMessageResponse, error)
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServiceServer struct{}

func (UnimplementedChatServiceServer) SendPrivateMessage(context.Context, *SendPrivateMessageRequest) (*SendPrivateMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPrivateMessage not implemented")
}
func (UnimplementedChatServiceServer) GetPrivateChatHistory(context.Context, *GetPrivateChatHistoryRequest) (*GetPrivateChatHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrivateChatHistory not implemented")
}
func (UnimplementedChatServiceServer) SearchPrivateMessages(context.Context, *SearchPrivateMessagesRequest) (*SearchPrivateMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchPrivateMessages not implemented")
}
func (UnimplementedChatServiceServer) RevokePrivateMessage(context.Context, *RevokePrivateMessageRequest) (*RevokePrivateMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokePrivateMessage not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}
func (UnimplementedChatServiceServer) testEmbeddedByValue()                     {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	// If the following call pancis, it indicates UnimplementedChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_SendPrivateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPrivateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SendPrivateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SendPrivateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SendPrivateMessage(ctx, req.(*SendPrivateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetPrivateChatHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrivateChatHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetPrivateChatHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetPrivateChatHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetPrivateChatHistory(ctx, req.(*GetPrivateChatHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SearchPrivateMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPrivateMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SearchPrivateMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SearchPrivateMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SearchPrivateMessages(ctx, req.(*SearchPrivateMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_RevokePrivateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokePrivateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).RevokePrivateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_RevokePrivateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).RevokePrivateMessage(ctx, req.(*RevokePrivateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPrivateMessage",
			Handler:    _ChatService_SendPrivateMessage_Handler,
		},
		{
			MethodName: "GetPrivateChatHistory",
			Handler:    _ChatService_GetPrivateChatHistory_Handler,
		},
		{
			MethodName: "SearchPrivateMessages",
			Handler:    _ChatService_SearchPrivateMessages_Handler,
		},
		{
			MethodName: "RevokePrivateMessage",
			Handler:    _ChatService_RevokePrivateMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat.proto",
}
