// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: chat.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 私聊消息内容，贴合 internal/model.MessageContent
type MessageContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          int32                  `protobuf:"varint,1,opt,name=kind,proto3" json:"kind,omitempty"`      // At, PlainText, Image
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 文本或资源地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageContent) Reset() {
	*x = MessageContent{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContent) ProtoMessage() {}

func (x *MessageContent) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContent.ProtoReflect.Descriptor instead.
func (*MessageContent) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *MessageContent) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *MessageContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 私聊消息/历史，贴合 internal/model.PrivateChatHistory / PrivateChatMessage
type PrivateChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderUid     int64                  `protobuf:"varint,2,opt,name=sender_uid,json=senderUid,proto3" json:"sender_uid,omitempty"`
	ReceiverUid   int64                  `protobuf:"varint,3,opt,name=receiver_uid,json=receiverUid,proto3" json:"receiver_uid,omitempty"`
	QuoteReply    int64                  `protobuf:"varint,4,opt,name=quote_reply,json=quoteReply,proto3" json:"quote_reply,omitempty"`
	Contents      []*MessageContent      `protobuf:"bytes,5,rep,name=contents,proto3" json:"contents,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Extensions    map[string]string      `protobuf:"bytes,8,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateChatMessage) Reset() {
	*x = PrivateChatMessage{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateChatMessage) ProtoMessage() {}

func (x *PrivateChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateChatMessage.ProtoReflect.Descriptor instead.
func (*PrivateChatMessage) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *PrivateChatMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PrivateChatMessage) GetSenderUid() int64 {
	if x != nil {
		return x.SenderUid
	}
	return 0
}

func (x *PrivateChatMessage) GetReceiverUid() int64 {
	if x != nil {
		return x.ReceiverUid
	}
	return 0
}

func (x *PrivateChatMessage) GetQuoteReply() int64 {
	if x != nil {
		return x.QuoteReply
	}
	return 0
}

func (x *PrivateChatMessage) GetContents() []*MessageContent {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *PrivateChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PrivateChatMessage) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PrivateChatMessage) GetExtensions() map[string]string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// 发送
type SendPrivateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *PrivateChatMessage    `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPrivateMessageRequest) Reset() {
	*x = SendPrivateMessageRequest{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPrivateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPrivateMessageRequest) ProtoMessage() {}

func (x *SendPrivateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPrivateMessageRequest.ProtoReflect.Descriptor instead.
func (*SendPrivateMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *SendPrivateMessageRequest) GetMessage() *PrivateChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type SendPrivateMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPrivateMessageResponse) Reset() {
	*x = SendPrivateMessageResponse{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPrivateMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPrivateMessageResponse) ProtoMessage() {}

func (x *SendPrivateMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPrivateMessageResponse.ProtoReflect.Descriptor instead.
func (*SendPrivateMessageResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *SendPrivateMessageResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SendPrivateMessageResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 拉取历史
type GetPrivateChatHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderUid     int64                  `protobuf:"varint,1,opt,name=sender_uid,json=senderUid,proto3" json:"sender_uid,omitempty"`
	ReceiverUid   int64                  `protobuf:"varint,2,opt,name=receiver_uid,json=receiverUid,proto3" json:"receiver_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivateChatHistoryRequest) Reset() {
	*x = GetPrivateChatHistoryRequest{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivateChatHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateChatHistoryRequest) ProtoMessage() {}

func (x *GetPrivateChatHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateChatHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetPrivateChatHistoryRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *GetPrivateChatHistoryRequest) GetSenderUid() int64 {
	if x != nil {
		return x.SenderUid
	}
	return 0
}

func (x *GetPrivateChatHistoryRequest) GetReceiverUid() int64 {
	if x != nil {
		return x.ReceiverUid
	}
	return 0
}

type GetPrivateChatHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*PrivateChatMessage  `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivateChatHistoryResponse) Reset() {
	*x = GetPrivateChatHistoryResponse{}
	mi := &file_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivateChatHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateChatHistoryResponse) ProtoMessage() {}

func (x *GetPrivateChatHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateChatHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetPrivateChatHistoryResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *GetPrivateChatHistoryResponse) GetMessages() []*PrivateChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// 搜索
type SearchPrivateMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderUid     int64                  `protobuf:"varint,1,opt,name=sender_uid,json=senderUid,proto3" json:"sender_uid,omitempty"`
	ReceiverUid   int64                  `protobuf:"varint,2,opt,name=receiver_uid,json=receiverUid,proto3" json:"receiver_uid,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPrivateMessagesRequest) Reset() {
	*x = SearchPrivateMessagesRequest{}
	mi := &file_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPrivateMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPrivateMessagesRequest) ProtoMessage() {}

func (x *SearchPrivateMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPrivateMessagesRequest.ProtoReflect.Descriptor instead.
func (*SearchPrivateMessagesRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

func (x *SearchPrivateMessagesRequest) GetSenderUid() int64 {
	if x != nil {
		return x.SenderUid
	}
	return 0
}

func (x *SearchPrivateMessagesRequest) GetReceiverUid() int64 {
	if x != nil {
		return x.ReceiverUid
	}
	return 0
}

func (x *SearchPrivateMessagesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type SearchPrivateMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*PrivateChatMessage  `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPrivateMessagesResponse) Reset() {
	*x = SearchPrivateMessagesResponse{}
	mi := &file_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPrivateMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPrivateMessagesResponse) ProtoMessage() {}

func (x *SearchPrivateMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPrivateMessagesResponse.ProtoReflect.Descriptor instead.
func (*SearchPrivateMessagesResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{7}
}

func (x *SearchPrivateMessagesResponse) GetMessages() []*PrivateChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// 撤回（占位）
type RevokePrivateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokePrivateMessageRequest) Reset() {
	*x = RevokePrivateMessageRequest{}
	mi := &file_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokePrivateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokePrivateMessageRequest) ProtoMessage() {}

func (x *RevokePrivateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokePrivateMessageRequest.ProtoReflect.Descriptor instead.
func (*RevokePrivateMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{8}
}

func (x *RevokePrivateMessageRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RevokePrivateMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokePrivateMessageResponse) Reset() {
	*x = RevokePrivateMessageResponse{}
	mi := &file_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokePrivateMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokePrivateMessageResponse) ProtoMessage() {}

func (x *RevokePrivateMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokePrivateMessageResponse.ProtoReflect.Descriptor instead.
func (*RevokePrivateMessageResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{9}
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\x04chat\">\n" +
	"\x0eMessageContent\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\x05R\x04kind\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xf8\x02\n" +
	"\x12PrivateChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"sender_uid\x18\x02 \x01(\x03R\tsenderUid\x12!\n" +
	"\freceiver_uid\x18\x03 \x01(\x03R\vreceiverUid\x12\x1f\n" +
	"\vquote_reply\x18\x04 \x01(\x03R\n" +
	"quoteReply\x120\n" +
	"\bcontents\x18\x05 \x03(\v2\x14.chat.MessageContentR\bcontents\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12H\n" +
	"\n" +
	"extensions\x18\b \x03(\v2(.chat.PrivateChatMessage.ExtensionsEntryR\n" +
	"extensions\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x19SendPrivateMessageRequest\x122\n" +
	"\amessage\x18\x01 \x01(\v2\x18.chat.PrivateChatMessageR\amessage\"<\n" +
	"\x1aSendPrivateMessageResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"`\n" +
	"\x1cGetPrivateChatHistoryRequest\x12\x1d\n" +
	"\n" +
	"sender_uid\x18\x01 \x01(\x03R\tsenderUid\x12!\n" +
	"\freceiver_uid\x18\x02 \x01(\x03R\vreceiverUid\"U\n" +
	"\x1dGetPrivateChatHistoryResponse\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.chat.PrivateChatMessageR\bmessages\"z\n" +
	"\x1cSearchPrivateMessagesRequest\x12\x1d\n" +
	"\n" +
	"sender_uid\x18\x01 \x01(\x03R\tsenderUid\x12!\n" +
	"\freceiver_uid\x18\x02 \x01(\x03R\vreceiverUid\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\"U\n" +
	"\x1dSearchPrivateMessagesResponse\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.chat.PrivateChatMessageR\bmessages\"-\n" +
	"\x1bRevokePrivateMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1e\n" +
	"\x1cRevokePrivateMessageResponse2\x89\x03\n" +
	"\vChatService\x12W\n" +
	"\x12SendPrivateMessage\x12\x1f.chat.SendPrivateMessageRequest\x1a .chat.SendPrivateMessageResponse\x12`\n" +
	"\x15GetPrivateChatHistory\x12\".chat.GetPrivateChatHistoryRequest\x1a#.chat.GetPrivateChatHistoryResponse\x12`\n" +
	"\x15SearchPrivateMessages\x12\".chat.SearchPrivateMessagesRequest\x1a#.chat.SearchPrivateMessagesResponse\x12]\n" +
	"\x14RevokePrivateMessage\x12!.chat.RevokePrivateMessageRequest\x1a\".chat.RevokePrivateMessageResponseB9Z7github.com/muxi-Infra/MUXI-IM-be/chat_service/grpc;grpcb\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_chat_proto_goTypes = []any{
	(*MessageContent)(nil),                // 0: chat.MessageContent
	(*PrivateChatMessage)(nil),            // 1: chat.PrivateChatMessage
	(*SendPrivateMessageRequest)(nil),     // 2: chat.SendPrivateMessageRequest
	(*SendPrivateMessageResponse)(nil),    // 3: chat.SendPrivateMessageResponse
	(*GetPrivateChatHistoryRequest)(nil),  // 4: chat.GetPrivateChatHistoryRequest
	(*GetPrivateChatHistoryResponse)(nil), // 5: chat.GetPrivateChatHistoryResponse
	(*SearchPrivateMessagesRequest)(nil),  // 6: chat.SearchPrivateMessagesRequest
	(*SearchPrivateMessagesResponse)(nil), // 7: chat.SearchPrivateMessagesResponse
	(*RevokePrivateMessageRequest)(nil),   // 8: chat.RevokePrivateMessageRequest
	(*RevokePrivateMessageResponse)(nil),  // 9: chat.RevokePrivateMessageResponse
	nil,                                   // 10: chat.PrivateChatMessage.ExtensionsEntry
}
var file_chat_proto_depIdxs = []int32{
	0,  // 0: chat.PrivateChatMessage.contents:type_name -> chat.MessageContent
	10, // 1: chat.PrivateChatMessage.extensions:type_name -> chat.PrivateChatMessage.ExtensionsEntry
	1,  // 2: chat.SendPrivateMessageRequest.message:type_name -> chat.PrivateChatMessage
	1,  // 3: chat.GetPrivateChatHistoryResponse.messages:type_name -> chat.PrivateChatMessage
	1,  // 4: chat.SearchPrivateMessagesResponse.messages:type_name -> chat.PrivateChatMessage
	2,  // 5: chat.ChatService.SendPrivateMessage:input_type -> chat.SendPrivateMessageRequest
	4,  // 6: chat.ChatService.GetPrivateChatHistory:input_type -> chat.GetPrivateChatHistoryRequest
	6,  // 7: chat.ChatService.SearchPrivateMessages:input_type -> chat.SearchPrivateMessagesRequest
	8,  // 8: chat.ChatService.RevokePrivateMessage:input_type -> chat.RevokePrivateMessageRequest
	3,  // 9: chat.ChatService.SendPrivateMessage:output_type -> chat.SendPrivateMessageResponse
	5,  // 10: chat.ChatService.GetPrivateChatHistory:output_type -> chat.GetPrivateChatHistoryResponse
	7,  // 11: chat.ChatService.SearchPrivateMessages:output_type -> chat.SearchPrivateMessagesResponse
	9,  // 12: chat.ChatService.RevokePrivateMessage:output_type -> chat.RevokePrivateMessageResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
